name: iklin
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  gap: ^2.0.0
  device_preview: ^1.1.0
  flutter_svg: ^1.1.5
  pin_code_fields: ^7.4.0
  dotted_border: ^2.0.0+2
  carousel_slider: ^4.1.1
  fl_chart: ^0.41.0
  syncfusion_flutter_datepicker: ^20.3.59
  intl: ^0.18.0
  flutter_rating_bar: ^4.0.1
  flutter_credit_card: ^3.0.4
  get_it: ^7.2.0
  injectable: ^2.1.0
  awesome_dialog: ^3.0.2
 
  internet_connection_checker: ^1.0.0+1
  logger: ^1.1.0
  dio: ^5.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  flutter_secure_storage: ^8.0.0
  flutter_launcher_icons: ^0.11.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  another_flushbar: ^1.12.29
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.4
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/IklinLogo.png
  

  android_12:
    image: assets/images/IklinLogo.png
    icon_background_color: "#ffffff"
   

  web: false
  ios: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/IklinLogo2.png"
  min_sdk_android: 21 
flutter:
  fonts:
    - family: Euclid
      fonts:
        - asset: assets/font/Euclid Circular A Bold Italic.ttf
        - asset: assets/font/Euclid Circular A Bold.ttf
        - asset: assets/font/Euclid Circular A Italic.ttf
        - asset: assets/font/Euclid Circular A Light Italic.ttf
        - asset: assets/font/Euclid Circular A Light.ttf
        - asset: assets/font/Euclid Circular A Medium Italic.ttf
        - asset: assets/font/Euclid Circular A Medium.ttf
        - asset: assets/font/Euclid Circular A Regular.ttf
        - asset: assets/font/Euclid Circular A SemiBold Italic.ttf
        - asset: assets/font/Euclid Circular A SemiBold.ttf






  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/